# Generated by Django 4.0.1 on 2022-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_alter_brand_imges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='brand',
            name='imges',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
    ]
