# Generated by Django 4.0.1 on 2022-01-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Orgin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Descreption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Expir_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Kind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
